### ISSUE TITLE
Поменять цвет текста

### ISSUE THREAD

**Issue by mushroomsPink** [Seal-Pavel/halloween_vegan_backend#1]
1. Открыть https://seal-pavel.website/admin/recipes/recipe/add/ 
2. Зайти в свой аккаунт.
3. Пройти по пути Home>Recipes>>Add recipe
4. Найти раздел Participant.
5. Поменять цвет текста с серого, плохо очень видно на чёрном фоне.

![2024-04-16_01-27-45](https://github.com/Seal-Pavel/halloween_vegan_backend/assets/135231099/662f6e32-2e85-4d45-a054-bd6e52134f29)

**Comment by mushroomsPink** [comment]
1. Открыть https://seal-pavel.website/admin/recipes/recipe/add/ 
2. Зайти в свой аккаунт.
3. Пройти по пути Home>Recipes>>Add recipe
4. Найти раздел Category.
5. Было бы хорошо сделать выпадающее меню с категориями, не понятно что писать..


![2024-04-16_01-34-38](https://github.com/Seal-Pavel/halloween_vegan_backend/assets/135231099/17eb05c6-e30a-44f8-ba1e-5a37f3a3ca3c)

**Comment by Seal-Pavel** [comment]
Проверь, пожалуйста.

**Comment by mushroomsPink** [comment]
Я так понял ты хочешь сделать контрастными через один. Может тогда там где белый фон сделать чёрный текст, а там где чёрный - белый?

![image](https://github.com/Seal-Pavel/halloween_vegan_backend/assets/135231099/fbf9b507-03ed-4e47-ad5a-4fffe1921e83)

**Comment by mushroomsPink** [comment]
Остались ещё, сделаешь их тоже белыми?

![image](https://github.com/Seal-Pavel/halloween_vegan_backend/assets/135231099/299e4e35-50f4-4806-86cf-c922e9a620d1)
![image](https://github.com/Seal-Pavel/halloween_vegan_backend/assets/135231099/5b8178b7-093f-43bc-ab5b-d95ba063417f)

**Comment by Seal-Pavel** [comment]
@mushroomsPink 
Чекни, пожалуйста)

**Comment by mushroomsPink** [comment]
Готово!
